// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqoO3xailinPHm6GOWMtkXIuMmLy9zY8M',
    appId: '1:315881569316:web:96f047264a5bbf270b2cb1',
    messagingSenderId: '315881569316',
    projectId: 'homecare-demo',
    authDomain: 'homecare-demo.firebaseapp.com',
    storageBucket: 'homecare-demo.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB90H-OZLCdRxFiPwclItyHTH0A3zqwK_E',
    appId: '1:315881569316:ios:ad3f2d4cab9409390b2cb1',
    messagingSenderId: '315881569316',
    projectId: 'homecare-demo',
    storageBucket: 'homecare-demo.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqoO3xailinPHm6GOWMtkXIuMmLy9zY8M',
    appId: '1:315881569316:web:e5459f354d30b0e20b2cb1',
    messagingSenderId: '315881569316',
    projectId: 'homecare-demo',
    authDomain: 'homecare-demo.firebaseapp.com',
    storageBucket: 'homecare-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB90H-OZLCdRxFiPwclItyHTH0A3zqwK_E',
    appId: '1:315881569316:ios:ad3f2d4cab9409390b2cb1',
    messagingSenderId: '315881569316',
    projectId: 'homecare-demo',
    storageBucket: 'homecare-demo.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKwKqjEOYlxu4WY412EJxBgN64TEgLu4E',
    appId: '1:315881569316:android:64f4e88b6d5ff6c20b2cb1',
    messagingSenderId: '315881569316',
    projectId: 'homecare-demo',
    storageBucket: 'homecare-demo.firebasestorage.app',
  );

}